changeLogFile=changelog/db.changelog-master.yaml

url=jdbc:sqlserver://host.docker.internal:1433;databaseName=sy-water-db;encrypt=true;trustServerCertificate=true

driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

liquibaseSchemaName=places

contexts=seed